spring:
  application:
    name: simple-web
  profiles:
    active: dev
server:
  port: 8000
# actuator http://localhost:8080/actuator
management:
  endpoint:
    shutdown:
      enabled: on
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,shutdown
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: prod